"""
Django settings for userproject project.

Generated by 'django-admin startproject' using Django 4.2.

For full documentation, visit:
https://docs.djangoproject.com/en/4.2/
"""

from pathlib import Path
import os

# -------------------------------------------------
# ✅ Base Directory
# -------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------
# ✅ Security Settings
# -------------------------------------------------
import environ
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=["localhost", "127.0.0.1"])



# -------------------------------------------------
# ✅ Installed Applications
# -------------------------------------------------
INSTALLED_APPS = [
    "jazzmin",  # 🚀 Modern Admin Panel UI
    "home.apps.HomeConfig",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'widget_tweaks',
    "import_export",  # For CSV export functionality
]

# -------------------------------------------------
# ✅ Middleware
# -------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django.middleware.security.SecurityMiddleware",
]

# -------------------------------------------------
# ✅ URL Configuration
# -------------------------------------------------
ROOT_URLCONF = "userproject.urls"

# -------------------------------------------------
# ✅ Templates
# -------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# -------------------------------------------------
# ✅ WSGI
# -------------------------------------------------
WSGI_APPLICATION = "userproject.wsgi.application"

# -------------------------------------------------
# ✅ Email Backend (for dev/testing)
# -------------------------------------------------
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")


ALLOWED_QR_CODE = "Tushar singh"

import dj_database_url

# -------------------------------------------------
# ✅ Database
# -------------------------------------------------
DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}

# -------------------------------------------------
# ✅ Password Validation
# -------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------
# ✅ Internationalization
# -------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# 12-hour time format settings
TIME_FORMAT = 'h:i A'
DATETIME_FORMAT = 'N j, Y, h:i A'
USE_L10N = False # Force custom formats

# -------------------------------------------------
# ✅ Static Files
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# -------------------------------------------------
STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    # "/var/www/static/",  # Optional custom path
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# STATIC_ROOT = BASE_DIR / "staticfiles"  # Uncomment during deployment
STATIC_ROOT = BASE_DIR / "staticfiles"


# -------------------------------------------------
# ✅ Media Files (Optional)
# -------------------------------------------------
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# -------------------------------------------------
# ✅ Authentication & Redirects
# -------------------------------------------------
LOGIN_REDIRECT_URL = "/redirect-after-login/"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"


# -------------------------------------------------
# ✅ Default Primary Key Field Type
# -------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# -------------------------------------------------
# ✅ Jazzmin Admin UI Settings
# -------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Pulse Admin",
    "site_header": "Pulse Attendance",
    "site_brand": "Pulse Core",
    "welcome_sign": "Welcome to the Deep Pulse Core",
    "copyright": "Pulse Attendance System",
    "search_model": ["auth.User"],
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "Return to Dashboard",  "url": "admin_dashboard", "permissions": ["auth.view_user"]},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "lumen",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
